### ISSUE TITLE
Attribute has already been defined exception when using lib with compile ('com.doomonafireball.betterpickers:library:1.5.2')

### ISSUE THREAD

**Issue by depodefi** [BoD/android-switch-backport#42]
There is conflict in my project when I try to use this library with compile betterpickers library. Gradle report following error:

Error:Attribute "switchStyle" has already been defined
Error:Attribute "switchPreferenceStyle" has already been defined

**Comment by rvganesh** [comment]
you can change the attribute name . After change the name its working fine for me.
newtrack
newthumbTextPadding
newswitchTextAppearance
newswitchMinWidth
newswitchPadding

**Comment by StringMon** [comment]
I'm still experiencing this using v1.5.4:

Error:(1) Attribute "track" has already been defined
Error:(1) Attribute "thumbTextPadding" has already been defined
Error:(1) Attribute "switchTextAppearance" has already been defined
Error:(1) Attribute "switchMinWidth" has already been defined
Error:(1) Attribute "switchPadding" has already been defined
Error:(1) Attribute "switchStyle" has already been defined

FWIW, here's the relevant section from my build.gradle:

dependencies {
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile ("com.doomonafireball.betterpickers:library:1.5.4") {
        exclude group: 'com.android.support', module: 'appcompat-v7'
    }
}

Any ideas?

**Comment by smaspe** [comment]
the issue still exists in 1.5.4

**Comment by StringMon** [comment]
@smaspe what I've found is that the issue exists *again* in 1.5.4. Try falling back to 1.5.3, that fixed it for me.

**Comment by deronbrown** [comment]
@StringMon @smaspe I think the issue with 1.5.4 is coming from android-switch-backport 1.3.1. Update switch-backport to 1.4.0 (make sure you change all of your `mavenCentral()` references to `jcenter()`).

**Comment by fchauveau** [comment]
@smaspe @rvganesh @uday12kumar Can you prodive a sample project where the problème is present. Because i don't get this issue, so it hard to fix it.
Thx

**Comment by nupurkumar** [comment]
@rvganesh In what file did you change the attribute names?

**Comment by marianosk** [comment]
@StringMon falling back to 1.5.3 solved this issue for me. Thanks a lot!
