### ISSUE TITLE
OnPreferenceChange return False, Switch Changes

### ISSUE THREAD

**Issue by McPo** [BoD/android-switch-backport#47]
When an OnPreferenceChangeListener returns false the switch should not be triggered.

What currently happens is the switch is moved to the ON position, but remains dull.
The switch correctly doesnt lightup but it shouldnt even move position. This gives the illusion that the switch is On, when in fact it is not.

This was verified against the built-in switch, with the backport using the default style.

**Comment by LittleHuba** [comment]
Anything new on this issue? I have the same problem.

**Comment by McPo** [comment]
Latest version not longer appears to suffer from this issue

**Comment by jegadeesan14mca** [comment]
The same problem I'm facing now. 
OnPreferenceChangeListener perfectly work on API version 21. But I had this issue in API level 19
